site_name: gramandha-Docs
repo_name: gramandha/gramandha-docs
repo_url: https://github.com/gramandha/gramandha-docs
extra_css:
  - stylesheets/extra.css
theme:
  nav:
    - Home: index.md
    - Doumentasi Repo 1:
        - README: repo1/README.md
        - Dokumentasi: repo1/docs.md
  features:
    - navigation.path
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      # accent: light red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav: 
  - Home: index.md
  - YOLO: test.md
  # - About: about.md